export const EXPENSE_CATEGORIES = [
  { id: "food", name: "Food & Dining", emoji: "🍕", color: "#EF4444" },
  { id: "transport", name: "Transportation", emoji: "🚗", color: "#F59E0B" },
  { id: "shopping", name: "Shopping", emoji: "🛍️", color: "#EC4899" },
  { id: "entertainment", name: "Entertainment", emoji: "🎬", color: "#8B5CF6" },
  { id: "bills", name: "Bills & Utilities", emoji: "💡", color: "#3B82F6" },
  { id: "health", name: "Health", emoji: "💊", color: "#10B981" },
  { id: "education", name: "Education", emoji: "📚", color: "#6366F1" },
  { id: "travel", name: "Travel", emoji: "✈️", color: "#06B6D4" },
  { id: "investment", name: "Investment", emoji: "📈", color: "#14B8A6" },
  { id: "rent", name: "Rent", emoji: "🏠", color: "#A855F7" },
  { id: "emi", name: "EMI / Loans", emoji: "💳", color: "#DC2626" },
  { id: "insurance", name: "Insurance", emoji: "🛡️", color: "#0EA5E9" },
  { id: "tax", name: "Taxes", emoji: "🧾", color: "#F97316" },
  { id: "subscriptions", name: "Subscriptions", emoji: "📺", color: "#7C3AED" },
  { id: "personal-care", name: "Personal Care", emoji: "🧴", color: "#F43F5E" },
  { id: "gifts", name: "Gifts & Donations", emoji: "🎁", color: "#E11D48" },
  { id: "family", name: "Family Expenses", emoji: "👨‍👩‍👧‍👦", color: "#9333EA" },
  { id: "others", name: "Others", emoji: "📦", color: "#64748B" },
];

export const INCOME_CATEGORIES = [
  { id: "salary", name: "Salary", emoji: "💰", color: "#10B981" },
  { id: "freelance", name: "Freelance", emoji: "💼", color: "#3B82F6" },
  { id: "business", name: "Business", emoji: "📊", color: "#8B5CF6" },
  {
    id: "investment_return",
    name: "Investment Returns",
    emoji: "📈",
    color: "#14B8A6",
  },
  { id: "gift", name: "Gift/Prize", emoji: "🎁", color: "#EC4899" },
  { id: "refund", name: "Refund", emoji: "↩️", color: "#F59E0B" },
  { id: "loan_received", name: "Loan Received", emoji: "🤝", color: "#6366F1" },
  { id: "rental", name: "Rental Income", emoji: "🏠", color: "#06B6D4" },
  { id: "other_income", name: "Other Income", emoji: "💵", color: "#64748B" },
];
